/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2006Data struct for InlineResponse2006Data
type InlineResponse2006Data struct {
	// Link(s) extracted.
	Links *[]string `json:"links,omitempty"`
}

// NewInlineResponse2006Data instantiates a new InlineResponse2006Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2006Data() *InlineResponse2006Data {
	this := InlineResponse2006Data{}
	return &this
}

// NewInlineResponse2006DataWithDefaults instantiates a new InlineResponse2006Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2006DataWithDefaults() *InlineResponse2006Data {
	this := InlineResponse2006Data{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *InlineResponse2006Data) GetLinks() []string {
	if o == nil || o.Links == nil {
		var ret []string
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2006Data) GetLinksOk() (*[]string, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *InlineResponse2006Data) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []string and assigns it to the Links field.
func (o *InlineResponse2006Data) SetLinks(v []string) {
	o.Links = &v
}

func (o InlineResponse2006Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2006Data struct {
	value *InlineResponse2006Data
	isSet bool
}

func (v NullableInlineResponse2006Data) Get() *InlineResponse2006Data {
	return v.value
}

func (v *NullableInlineResponse2006Data) Set(val *InlineResponse2006Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2006Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2006Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2006Data(val *InlineResponse2006Data) *NullableInlineResponse2006Data {
	return &NullableInlineResponse2006Data{value: val, isSet: true}
}

func (v NullableInlineResponse2006Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2006Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


