/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20010DataMagnets struct for InlineResponse20010DataMagnets
type InlineResponse20010DataMagnets struct {
	Magnet *string `json:"magnet,omitempty"`
	Hash *string `json:"hash,omitempty"`
	Name *string `json:"name,omitempty"`
	Size *int64 `json:"size,omitempty"`
	Ready *bool `json:"ready,omitempty"`
	Id *int64 `json:"id,omitempty"`
	Error *InlineResponse20010DataError `json:"error,omitempty"`
}

// NewInlineResponse20010DataMagnets instantiates a new InlineResponse20010DataMagnets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20010DataMagnets() *InlineResponse20010DataMagnets {
	this := InlineResponse20010DataMagnets{}
	return &this
}

// NewInlineResponse20010DataMagnetsWithDefaults instantiates a new InlineResponse20010DataMagnets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20010DataMagnetsWithDefaults() *InlineResponse20010DataMagnets {
	this := InlineResponse20010DataMagnets{}
	return &this
}

// GetMagnet returns the Magnet field value if set, zero value otherwise.
func (o *InlineResponse20010DataMagnets) GetMagnet() string {
	if o == nil || o.Magnet == nil {
		var ret string
		return ret
	}
	return *o.Magnet
}

// GetMagnetOk returns a tuple with the Magnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20010DataMagnets) GetMagnetOk() (*string, bool) {
	if o == nil || o.Magnet == nil {
		return nil, false
	}
	return o.Magnet, true
}

// HasMagnet returns a boolean if a field has been set.
func (o *InlineResponse20010DataMagnets) HasMagnet() bool {
	if o != nil && o.Magnet != nil {
		return true
	}

	return false
}

// SetMagnet gets a reference to the given string and assigns it to the Magnet field.
func (o *InlineResponse20010DataMagnets) SetMagnet(v string) {
	o.Magnet = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *InlineResponse20010DataMagnets) GetHash() string {
	if o == nil || o.Hash == nil {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20010DataMagnets) GetHashOk() (*string, bool) {
	if o == nil || o.Hash == nil {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *InlineResponse20010DataMagnets) HasHash() bool {
	if o != nil && o.Hash != nil {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *InlineResponse20010DataMagnets) SetHash(v string) {
	o.Hash = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InlineResponse20010DataMagnets) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20010DataMagnets) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InlineResponse20010DataMagnets) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InlineResponse20010DataMagnets) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *InlineResponse20010DataMagnets) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20010DataMagnets) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *InlineResponse20010DataMagnets) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *InlineResponse20010DataMagnets) SetSize(v int64) {
	o.Size = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *InlineResponse20010DataMagnets) GetReady() bool {
	if o == nil || o.Ready == nil {
		var ret bool
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20010DataMagnets) GetReadyOk() (*bool, bool) {
	if o == nil || o.Ready == nil {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *InlineResponse20010DataMagnets) HasReady() bool {
	if o != nil && o.Ready != nil {
		return true
	}

	return false
}

// SetReady gets a reference to the given bool and assigns it to the Ready field.
func (o *InlineResponse20010DataMagnets) SetReady(v bool) {
	o.Ready = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineResponse20010DataMagnets) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20010DataMagnets) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineResponse20010DataMagnets) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *InlineResponse20010DataMagnets) SetId(v int64) {
	o.Id = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *InlineResponse20010DataMagnets) GetError() InlineResponse20010DataError {
	if o == nil || o.Error == nil {
		var ret InlineResponse20010DataError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20010DataMagnets) GetErrorOk() (*InlineResponse20010DataError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *InlineResponse20010DataMagnets) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given InlineResponse20010DataError and assigns it to the Error field.
func (o *InlineResponse20010DataMagnets) SetError(v InlineResponse20010DataError) {
	o.Error = &v
}

func (o InlineResponse20010DataMagnets) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Magnet != nil {
		toSerialize["magnet"] = o.Magnet
	}
	if o.Hash != nil {
		toSerialize["hash"] = o.Hash
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Ready != nil {
		toSerialize["ready"] = o.Ready
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20010DataMagnets struct {
	value *InlineResponse20010DataMagnets
	isSet bool
}

func (v NullableInlineResponse20010DataMagnets) Get() *InlineResponse20010DataMagnets {
	return v.value
}

func (v *NullableInlineResponse20010DataMagnets) Set(val *InlineResponse20010DataMagnets) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20010DataMagnets) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20010DataMagnets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20010DataMagnets(val *InlineResponse20010DataMagnets) *NullableInlineResponse20010DataMagnets {
	return &NullableInlineResponse20010DataMagnets{value: val, isSet: true}
}

func (v NullableInlineResponse20010DataMagnets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20010DataMagnets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


