/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2001Data struct for InlineResponse2001Data
type InlineResponse2001Data struct {
	Hosts *[]string `json:"hosts,omitempty"`
	Streams *[]string `json:"streams,omitempty"`
	Redirectors *[]string `json:"redirectors,omitempty"`
}

// NewInlineResponse2001Data instantiates a new InlineResponse2001Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2001Data() *InlineResponse2001Data {
	this := InlineResponse2001Data{}
	return &this
}

// NewInlineResponse2001DataWithDefaults instantiates a new InlineResponse2001Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2001DataWithDefaults() *InlineResponse2001Data {
	this := InlineResponse2001Data{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *InlineResponse2001Data) GetHosts() []string {
	if o == nil || o.Hosts == nil {
		var ret []string
		return ret
	}
	return *o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Data) GetHostsOk() (*[]string, bool) {
	if o == nil || o.Hosts == nil {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *InlineResponse2001Data) HasHosts() bool {
	if o != nil && o.Hosts != nil {
		return true
	}

	return false
}

// SetHosts gets a reference to the given []string and assigns it to the Hosts field.
func (o *InlineResponse2001Data) SetHosts(v []string) {
	o.Hosts = &v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *InlineResponse2001Data) GetStreams() []string {
	if o == nil || o.Streams == nil {
		var ret []string
		return ret
	}
	return *o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Data) GetStreamsOk() (*[]string, bool) {
	if o == nil || o.Streams == nil {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *InlineResponse2001Data) HasStreams() bool {
	if o != nil && o.Streams != nil {
		return true
	}

	return false
}

// SetStreams gets a reference to the given []string and assigns it to the Streams field.
func (o *InlineResponse2001Data) SetStreams(v []string) {
	o.Streams = &v
}

// GetRedirectors returns the Redirectors field value if set, zero value otherwise.
func (o *InlineResponse2001Data) GetRedirectors() []string {
	if o == nil || o.Redirectors == nil {
		var ret []string
		return ret
	}
	return *o.Redirectors
}

// GetRedirectorsOk returns a tuple with the Redirectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Data) GetRedirectorsOk() (*[]string, bool) {
	if o == nil || o.Redirectors == nil {
		return nil, false
	}
	return o.Redirectors, true
}

// HasRedirectors returns a boolean if a field has been set.
func (o *InlineResponse2001Data) HasRedirectors() bool {
	if o != nil && o.Redirectors != nil {
		return true
	}

	return false
}

// SetRedirectors gets a reference to the given []string and assigns it to the Redirectors field.
func (o *InlineResponse2001Data) SetRedirectors(v []string) {
	o.Redirectors = &v
}

func (o InlineResponse2001Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Hosts != nil {
		toSerialize["hosts"] = o.Hosts
	}
	if o.Streams != nil {
		toSerialize["streams"] = o.Streams
	}
	if o.Redirectors != nil {
		toSerialize["redirectors"] = o.Redirectors
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2001Data struct {
	value *InlineResponse2001Data
	isSet bool
}

func (v NullableInlineResponse2001Data) Get() *InlineResponse2001Data {
	return v.value
}

func (v *NullableInlineResponse2001Data) Set(val *InlineResponse2001Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2001Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2001Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2001Data(val *InlineResponse2001Data) *NullableInlineResponse2001Data {
	return &NullableInlineResponse2001Data{value: val, isSet: true}
}

func (v NullableInlineResponse2001Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2001Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


