/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse200DataStreams struct for InlineResponse200DataStreams
type InlineResponse200DataStreams struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Domains *[]string `json:"domains,omitempty"`
	Regexp *string `json:"regexp,omitempty"`
	Regexps *[]string `json:"regexps,omitempty"`
	Status *bool `json:"status,omitempty"`
}

// NewInlineResponse200DataStreams instantiates a new InlineResponse200DataStreams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200DataStreams() *InlineResponse200DataStreams {
	this := InlineResponse200DataStreams{}
	return &this
}

// NewInlineResponse200DataStreamsWithDefaults instantiates a new InlineResponse200DataStreams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200DataStreamsWithDefaults() *InlineResponse200DataStreams {
	this := InlineResponse200DataStreams{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InlineResponse200DataStreams) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200DataStreams) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InlineResponse200DataStreams) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InlineResponse200DataStreams) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InlineResponse200DataStreams) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200DataStreams) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InlineResponse200DataStreams) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *InlineResponse200DataStreams) SetType(v string) {
	o.Type = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *InlineResponse200DataStreams) GetDomains() []string {
	if o == nil || o.Domains == nil {
		var ret []string
		return ret
	}
	return *o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200DataStreams) GetDomainsOk() (*[]string, bool) {
	if o == nil || o.Domains == nil {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *InlineResponse200DataStreams) HasDomains() bool {
	if o != nil && o.Domains != nil {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *InlineResponse200DataStreams) SetDomains(v []string) {
	o.Domains = &v
}

// GetRegexp returns the Regexp field value if set, zero value otherwise.
func (o *InlineResponse200DataStreams) GetRegexp() string {
	if o == nil || o.Regexp == nil {
		var ret string
		return ret
	}
	return *o.Regexp
}

// GetRegexpOk returns a tuple with the Regexp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200DataStreams) GetRegexpOk() (*string, bool) {
	if o == nil || o.Regexp == nil {
		return nil, false
	}
	return o.Regexp, true
}

// HasRegexp returns a boolean if a field has been set.
func (o *InlineResponse200DataStreams) HasRegexp() bool {
	if o != nil && o.Regexp != nil {
		return true
	}

	return false
}

// SetRegexp gets a reference to the given string and assigns it to the Regexp field.
func (o *InlineResponse200DataStreams) SetRegexp(v string) {
	o.Regexp = &v
}

// GetRegexps returns the Regexps field value if set, zero value otherwise.
func (o *InlineResponse200DataStreams) GetRegexps() []string {
	if o == nil || o.Regexps == nil {
		var ret []string
		return ret
	}
	return *o.Regexps
}

// GetRegexpsOk returns a tuple with the Regexps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200DataStreams) GetRegexpsOk() (*[]string, bool) {
	if o == nil || o.Regexps == nil {
		return nil, false
	}
	return o.Regexps, true
}

// HasRegexps returns a boolean if a field has been set.
func (o *InlineResponse200DataStreams) HasRegexps() bool {
	if o != nil && o.Regexps != nil {
		return true
	}

	return false
}

// SetRegexps gets a reference to the given []string and assigns it to the Regexps field.
func (o *InlineResponse200DataStreams) SetRegexps(v []string) {
	o.Regexps = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InlineResponse200DataStreams) GetStatus() bool {
	if o == nil || o.Status == nil {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200DataStreams) GetStatusOk() (*bool, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InlineResponse200DataStreams) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *InlineResponse200DataStreams) SetStatus(v bool) {
	o.Status = &v
}

func (o InlineResponse200DataStreams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Domains != nil {
		toSerialize["domains"] = o.Domains
	}
	if o.Regexp != nil {
		toSerialize["regexp"] = o.Regexp
	}
	if o.Regexps != nil {
		toSerialize["regexps"] = o.Regexps
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200DataStreams struct {
	value *InlineResponse200DataStreams
	isSet bool
}

func (v NullableInlineResponse200DataStreams) Get() *InlineResponse200DataStreams {
	return v.value
}

func (v *NullableInlineResponse200DataStreams) Set(val *InlineResponse200DataStreams) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200DataStreams) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200DataStreams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200DataStreams(val *InlineResponse200DataStreams) *NullableInlineResponse200DataStreams {
	return &NullableInlineResponse200DataStreams{value: val, isSet: true}
}

func (v NullableInlineResponse200DataStreams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200DataStreams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


