/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20014DataMagnets struct for InlineResponse20014DataMagnets
type InlineResponse20014DataMagnets struct {
	Magnet *string `json:"magnet,omitempty"`
	Message *string `json:"message,omitempty"`
	Error *InlineResponse20014DataError `json:"error,omitempty"`
}

// NewInlineResponse20014DataMagnets instantiates a new InlineResponse20014DataMagnets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20014DataMagnets() *InlineResponse20014DataMagnets {
	this := InlineResponse20014DataMagnets{}
	return &this
}

// NewInlineResponse20014DataMagnetsWithDefaults instantiates a new InlineResponse20014DataMagnets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20014DataMagnetsWithDefaults() *InlineResponse20014DataMagnets {
	this := InlineResponse20014DataMagnets{}
	return &this
}

// GetMagnet returns the Magnet field value if set, zero value otherwise.
func (o *InlineResponse20014DataMagnets) GetMagnet() string {
	if o == nil || o.Magnet == nil {
		var ret string
		return ret
	}
	return *o.Magnet
}

// GetMagnetOk returns a tuple with the Magnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20014DataMagnets) GetMagnetOk() (*string, bool) {
	if o == nil || o.Magnet == nil {
		return nil, false
	}
	return o.Magnet, true
}

// HasMagnet returns a boolean if a field has been set.
func (o *InlineResponse20014DataMagnets) HasMagnet() bool {
	if o != nil && o.Magnet != nil {
		return true
	}

	return false
}

// SetMagnet gets a reference to the given string and assigns it to the Magnet field.
func (o *InlineResponse20014DataMagnets) SetMagnet(v string) {
	o.Magnet = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InlineResponse20014DataMagnets) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20014DataMagnets) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InlineResponse20014DataMagnets) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InlineResponse20014DataMagnets) SetMessage(v string) {
	o.Message = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *InlineResponse20014DataMagnets) GetError() InlineResponse20014DataError {
	if o == nil || o.Error == nil {
		var ret InlineResponse20014DataError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20014DataMagnets) GetErrorOk() (*InlineResponse20014DataError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *InlineResponse20014DataMagnets) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given InlineResponse20014DataError and assigns it to the Error field.
func (o *InlineResponse20014DataMagnets) SetError(v InlineResponse20014DataError) {
	o.Error = &v
}

func (o InlineResponse20014DataMagnets) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Magnet != nil {
		toSerialize["magnet"] = o.Magnet
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20014DataMagnets struct {
	value *InlineResponse20014DataMagnets
	isSet bool
}

func (v NullableInlineResponse20014DataMagnets) Get() *InlineResponse20014DataMagnets {
	return v.value
}

func (v *NullableInlineResponse20014DataMagnets) Set(val *InlineResponse20014DataMagnets) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20014DataMagnets) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20014DataMagnets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20014DataMagnets(val *InlineResponse20014DataMagnets) *NullableInlineResponse20014DataMagnets {
	return &NullableInlineResponse20014DataMagnets{value: val, isSet: true}
}

func (v NullableInlineResponse20014DataMagnets) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20014DataMagnets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


