/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2005DataInfos struct for InlineResponse2005DataInfos
type InlineResponse2005DataInfos struct {
	// Requested link
	Link *string `json:"link,omitempty"`
	// Link's file filename.
	Filename *string `json:"filename,omitempty"`
	// Link's file size in bytes.
	Size *int64 `json:"size,omitempty"`
	// Link host.
	Host *string `json:"host,omitempty"`
	// Host main domain
	HostDomain *string `json:"hostDomain,omitempty"`
}

// NewInlineResponse2005DataInfos instantiates a new InlineResponse2005DataInfos object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2005DataInfos() *InlineResponse2005DataInfos {
	this := InlineResponse2005DataInfos{}
	return &this
}

// NewInlineResponse2005DataInfosWithDefaults instantiates a new InlineResponse2005DataInfos object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2005DataInfosWithDefaults() *InlineResponse2005DataInfos {
	this := InlineResponse2005DataInfos{}
	return &this
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *InlineResponse2005DataInfos) GetLink() string {
	if o == nil || o.Link == nil {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005DataInfos) GetLinkOk() (*string, bool) {
	if o == nil || o.Link == nil {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *InlineResponse2005DataInfos) HasLink() bool {
	if o != nil && o.Link != nil {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *InlineResponse2005DataInfos) SetLink(v string) {
	o.Link = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *InlineResponse2005DataInfos) GetFilename() string {
	if o == nil || o.Filename == nil {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005DataInfos) GetFilenameOk() (*string, bool) {
	if o == nil || o.Filename == nil {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *InlineResponse2005DataInfos) HasFilename() bool {
	if o != nil && o.Filename != nil {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *InlineResponse2005DataInfos) SetFilename(v string) {
	o.Filename = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *InlineResponse2005DataInfos) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005DataInfos) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *InlineResponse2005DataInfos) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *InlineResponse2005DataInfos) SetSize(v int64) {
	o.Size = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *InlineResponse2005DataInfos) GetHost() string {
	if o == nil || o.Host == nil {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005DataInfos) GetHostOk() (*string, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *InlineResponse2005DataInfos) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *InlineResponse2005DataInfos) SetHost(v string) {
	o.Host = &v
}

// GetHostDomain returns the HostDomain field value if set, zero value otherwise.
func (o *InlineResponse2005DataInfos) GetHostDomain() string {
	if o == nil || o.HostDomain == nil {
		var ret string
		return ret
	}
	return *o.HostDomain
}

// GetHostDomainOk returns a tuple with the HostDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2005DataInfos) GetHostDomainOk() (*string, bool) {
	if o == nil || o.HostDomain == nil {
		return nil, false
	}
	return o.HostDomain, true
}

// HasHostDomain returns a boolean if a field has been set.
func (o *InlineResponse2005DataInfos) HasHostDomain() bool {
	if o != nil && o.HostDomain != nil {
		return true
	}

	return false
}

// SetHostDomain gets a reference to the given string and assigns it to the HostDomain field.
func (o *InlineResponse2005DataInfos) SetHostDomain(v string) {
	o.HostDomain = &v
}

func (o InlineResponse2005DataInfos) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Link != nil {
		toSerialize["link"] = o.Link
	}
	if o.Filename != nil {
		toSerialize["filename"] = o.Filename
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Host != nil {
		toSerialize["host"] = o.Host
	}
	if o.HostDomain != nil {
		toSerialize["hostDomain"] = o.HostDomain
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2005DataInfos struct {
	value *InlineResponse2005DataInfos
	isSet bool
}

func (v NullableInlineResponse2005DataInfos) Get() *InlineResponse2005DataInfos {
	return v.value
}

func (v *NullableInlineResponse2005DataInfos) Set(val *InlineResponse2005DataInfos) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2005DataInfos) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2005DataInfos) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2005DataInfos(val *InlineResponse2005DataInfos) *NullableInlineResponse2005DataInfos {
	return &NullableInlineResponse2005DataInfos{value: val, isSet: true}
}

func (v NullableInlineResponse2005DataInfos) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2005DataInfos) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


