/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20016DataLinks struct for InlineResponse20016DataLinks
type InlineResponse20016DataLinks struct {
	Link *string `json:"link,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Size *int64 `json:"size,omitempty"`
	Date *int64 `json:"date,omitempty"`
	Host *string `json:"host,omitempty"`
}

// NewInlineResponse20016DataLinks instantiates a new InlineResponse20016DataLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20016DataLinks() *InlineResponse20016DataLinks {
	this := InlineResponse20016DataLinks{}
	return &this
}

// NewInlineResponse20016DataLinksWithDefaults instantiates a new InlineResponse20016DataLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20016DataLinksWithDefaults() *InlineResponse20016DataLinks {
	this := InlineResponse20016DataLinks{}
	return &this
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *InlineResponse20016DataLinks) GetLink() string {
	if o == nil || o.Link == nil {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20016DataLinks) GetLinkOk() (*string, bool) {
	if o == nil || o.Link == nil {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *InlineResponse20016DataLinks) HasLink() bool {
	if o != nil && o.Link != nil {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *InlineResponse20016DataLinks) SetLink(v string) {
	o.Link = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *InlineResponse20016DataLinks) GetFilename() string {
	if o == nil || o.Filename == nil {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20016DataLinks) GetFilenameOk() (*string, bool) {
	if o == nil || o.Filename == nil {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *InlineResponse20016DataLinks) HasFilename() bool {
	if o != nil && o.Filename != nil {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *InlineResponse20016DataLinks) SetFilename(v string) {
	o.Filename = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *InlineResponse20016DataLinks) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20016DataLinks) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *InlineResponse20016DataLinks) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *InlineResponse20016DataLinks) SetSize(v int64) {
	o.Size = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *InlineResponse20016DataLinks) GetDate() int64 {
	if o == nil || o.Date == nil {
		var ret int64
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20016DataLinks) GetDateOk() (*int64, bool) {
	if o == nil || o.Date == nil {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *InlineResponse20016DataLinks) HasDate() bool {
	if o != nil && o.Date != nil {
		return true
	}

	return false
}

// SetDate gets a reference to the given int64 and assigns it to the Date field.
func (o *InlineResponse20016DataLinks) SetDate(v int64) {
	o.Date = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *InlineResponse20016DataLinks) GetHost() string {
	if o == nil || o.Host == nil {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20016DataLinks) GetHostOk() (*string, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *InlineResponse20016DataLinks) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *InlineResponse20016DataLinks) SetHost(v string) {
	o.Host = &v
}

func (o InlineResponse20016DataLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Link != nil {
		toSerialize["link"] = o.Link
	}
	if o.Filename != nil {
		toSerialize["filename"] = o.Filename
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Date != nil {
		toSerialize["date"] = o.Date
	}
	if o.Host != nil {
		toSerialize["host"] = o.Host
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20016DataLinks struct {
	value *InlineResponse20016DataLinks
	isSet bool
}

func (v NullableInlineResponse20016DataLinks) Get() *InlineResponse20016DataLinks {
	return v.value
}

func (v *NullableInlineResponse20016DataLinks) Set(val *InlineResponse20016DataLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20016DataLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20016DataLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20016DataLinks(val *InlineResponse20016DataLinks) *NullableInlineResponse20016DataLinks {
	return &NullableInlineResponse20016DataLinks{value: val, isSet: true}
}

func (v NullableInlineResponse20016DataLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20016DataLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


