/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20015Data struct for InlineResponse20015Data
type InlineResponse20015Data struct {
	Magnets *[]InlineResponse20015DataMagnets `json:"magnets,omitempty"`
}

// NewInlineResponse20015Data instantiates a new InlineResponse20015Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20015Data() *InlineResponse20015Data {
	this := InlineResponse20015Data{}
	return &this
}

// NewInlineResponse20015DataWithDefaults instantiates a new InlineResponse20015Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20015DataWithDefaults() *InlineResponse20015Data {
	this := InlineResponse20015Data{}
	return &this
}

// GetMagnets returns the Magnets field value if set, zero value otherwise.
func (o *InlineResponse20015Data) GetMagnets() []InlineResponse20015DataMagnets {
	if o == nil || o.Magnets == nil {
		var ret []InlineResponse20015DataMagnets
		return ret
	}
	return *o.Magnets
}

// GetMagnetsOk returns a tuple with the Magnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20015Data) GetMagnetsOk() (*[]InlineResponse20015DataMagnets, bool) {
	if o == nil || o.Magnets == nil {
		return nil, false
	}
	return o.Magnets, true
}

// HasMagnets returns a boolean if a field has been set.
func (o *InlineResponse20015Data) HasMagnets() bool {
	if o != nil && o.Magnets != nil {
		return true
	}

	return false
}

// SetMagnets gets a reference to the given []InlineResponse20015DataMagnets and assigns it to the Magnets field.
func (o *InlineResponse20015Data) SetMagnets(v []InlineResponse20015DataMagnets) {
	o.Magnets = &v
}

func (o InlineResponse20015Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Magnets != nil {
		toSerialize["magnets"] = o.Magnets
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20015Data struct {
	value *InlineResponse20015Data
	isSet bool
}

func (v NullableInlineResponse20015Data) Get() *InlineResponse20015Data {
	return v.value
}

func (v *NullableInlineResponse20015Data) Set(val *InlineResponse20015Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20015Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20015Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20015Data(val *InlineResponse20015Data) *NullableInlineResponse20015Data {
	return &NullableInlineResponse20015Data{value: val, isSet: true}
}

func (v NullableInlineResponse20015Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20015Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


