/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2007DataStreams struct for InlineResponse2007DataStreams
type InlineResponse2007DataStreams struct {
	Id *string `json:"id,omitempty"`
	Ext *string `json:"ext,omitempty"`
	Quality *string `json:"quality,omitempty"`
	Filesize *int64 `json:"filesize,omitempty"`
	Proto *string `json:"proto,omitempty"`
	Name *string `json:"name,omitempty"`
	Link *string `json:"link,omitempty"`
	Tb *float32 `json:"tb,omitempty"`
	Abr *int64 `json:"abr,omitempty"`
}

// NewInlineResponse2007DataStreams instantiates a new InlineResponse2007DataStreams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2007DataStreams() *InlineResponse2007DataStreams {
	this := InlineResponse2007DataStreams{}
	return &this
}

// NewInlineResponse2007DataStreamsWithDefaults instantiates a new InlineResponse2007DataStreams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2007DataStreamsWithDefaults() *InlineResponse2007DataStreams {
	this := InlineResponse2007DataStreams{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InlineResponse2007DataStreams) SetId(v string) {
	o.Id = &v
}

// GetExt returns the Ext field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetExt() string {
	if o == nil || o.Ext == nil {
		var ret string
		return ret
	}
	return *o.Ext
}

// GetExtOk returns a tuple with the Ext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetExtOk() (*string, bool) {
	if o == nil || o.Ext == nil {
		return nil, false
	}
	return o.Ext, true
}

// HasExt returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasExt() bool {
	if o != nil && o.Ext != nil {
		return true
	}

	return false
}

// SetExt gets a reference to the given string and assigns it to the Ext field.
func (o *InlineResponse2007DataStreams) SetExt(v string) {
	o.Ext = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetQuality() string {
	if o == nil || o.Quality == nil {
		var ret string
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetQualityOk() (*string, bool) {
	if o == nil || o.Quality == nil {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasQuality() bool {
	if o != nil && o.Quality != nil {
		return true
	}

	return false
}

// SetQuality gets a reference to the given string and assigns it to the Quality field.
func (o *InlineResponse2007DataStreams) SetQuality(v string) {
	o.Quality = &v
}

// GetFilesize returns the Filesize field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetFilesize() int64 {
	if o == nil || o.Filesize == nil {
		var ret int64
		return ret
	}
	return *o.Filesize
}

// GetFilesizeOk returns a tuple with the Filesize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetFilesizeOk() (*int64, bool) {
	if o == nil || o.Filesize == nil {
		return nil, false
	}
	return o.Filesize, true
}

// HasFilesize returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasFilesize() bool {
	if o != nil && o.Filesize != nil {
		return true
	}

	return false
}

// SetFilesize gets a reference to the given int64 and assigns it to the Filesize field.
func (o *InlineResponse2007DataStreams) SetFilesize(v int64) {
	o.Filesize = &v
}

// GetProto returns the Proto field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetProto() string {
	if o == nil || o.Proto == nil {
		var ret string
		return ret
	}
	return *o.Proto
}

// GetProtoOk returns a tuple with the Proto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetProtoOk() (*string, bool) {
	if o == nil || o.Proto == nil {
		return nil, false
	}
	return o.Proto, true
}

// HasProto returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasProto() bool {
	if o != nil && o.Proto != nil {
		return true
	}

	return false
}

// SetProto gets a reference to the given string and assigns it to the Proto field.
func (o *InlineResponse2007DataStreams) SetProto(v string) {
	o.Proto = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InlineResponse2007DataStreams) SetName(v string) {
	o.Name = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetLink() string {
	if o == nil || o.Link == nil {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetLinkOk() (*string, bool) {
	if o == nil || o.Link == nil {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasLink() bool {
	if o != nil && o.Link != nil {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *InlineResponse2007DataStreams) SetLink(v string) {
	o.Link = &v
}

// GetTb returns the Tb field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetTb() float32 {
	if o == nil || o.Tb == nil {
		var ret float32
		return ret
	}
	return *o.Tb
}

// GetTbOk returns a tuple with the Tb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetTbOk() (*float32, bool) {
	if o == nil || o.Tb == nil {
		return nil, false
	}
	return o.Tb, true
}

// HasTb returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasTb() bool {
	if o != nil && o.Tb != nil {
		return true
	}

	return false
}

// SetTb gets a reference to the given float32 and assigns it to the Tb field.
func (o *InlineResponse2007DataStreams) SetTb(v float32) {
	o.Tb = &v
}

// GetAbr returns the Abr field value if set, zero value otherwise.
func (o *InlineResponse2007DataStreams) GetAbr() int64 {
	if o == nil || o.Abr == nil {
		var ret int64
		return ret
	}
	return *o.Abr
}

// GetAbrOk returns a tuple with the Abr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2007DataStreams) GetAbrOk() (*int64, bool) {
	if o == nil || o.Abr == nil {
		return nil, false
	}
	return o.Abr, true
}

// HasAbr returns a boolean if a field has been set.
func (o *InlineResponse2007DataStreams) HasAbr() bool {
	if o != nil && o.Abr != nil {
		return true
	}

	return false
}

// SetAbr gets a reference to the given int64 and assigns it to the Abr field.
func (o *InlineResponse2007DataStreams) SetAbr(v int64) {
	o.Abr = &v
}

func (o InlineResponse2007DataStreams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Ext != nil {
		toSerialize["ext"] = o.Ext
	}
	if o.Quality != nil {
		toSerialize["quality"] = o.Quality
	}
	if o.Filesize != nil {
		toSerialize["filesize"] = o.Filesize
	}
	if o.Proto != nil {
		toSerialize["proto"] = o.Proto
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Link != nil {
		toSerialize["link"] = o.Link
	}
	if o.Tb != nil {
		toSerialize["tb"] = o.Tb
	}
	if o.Abr != nil {
		toSerialize["abr"] = o.Abr
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2007DataStreams struct {
	value *InlineResponse2007DataStreams
	isSet bool
}

func (v NullableInlineResponse2007DataStreams) Get() *InlineResponse2007DataStreams {
	return v.value
}

func (v *NullableInlineResponse2007DataStreams) Set(val *InlineResponse2007DataStreams) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2007DataStreams) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2007DataStreams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2007DataStreams(val *InlineResponse2007DataStreams) *NullableInlineResponse2007DataStreams {
	return &NullableInlineResponse2007DataStreams{value: val, isSet: true}
}

func (v NullableInlineResponse2007DataStreams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2007DataStreams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


