/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2003DataUser struct for InlineResponse2003DataUser
type InlineResponse2003DataUser struct {
	Username *string `json:"username,omitempty"`
	Email *string `json:"email,omitempty"`
	IsPremium *bool `json:"isPremium,omitempty"`
	IsSubscribed *bool `json:"isSubscribed,omitempty"`
	IsTrial *bool `json:"isTrial,omitempty"`
	PremiumUntil *int64 `json:"premiumUntil,omitempty"`
	Lang *string `json:"lang,omitempty"`
	PreferedDomain *string `json:"preferedDomain,omitempty"`
	FidelityPoints *int64 `json:"fidelityPoints,omitempty"`
	LimitedHostersQuotas *map[string]int64 `json:"limitedHostersQuotas,omitempty"`
	Notifications *[]string `json:"notifications,omitempty"`
}

// NewInlineResponse2003DataUser instantiates a new InlineResponse2003DataUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2003DataUser() *InlineResponse2003DataUser {
	this := InlineResponse2003DataUser{}
	return &this
}

// NewInlineResponse2003DataUserWithDefaults instantiates a new InlineResponse2003DataUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2003DataUserWithDefaults() *InlineResponse2003DataUser {
	this := InlineResponse2003DataUser{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *InlineResponse2003DataUser) SetUsername(v string) {
	o.Username = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *InlineResponse2003DataUser) SetEmail(v string) {
	o.Email = &v
}

// GetIsPremium returns the IsPremium field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetIsPremium() bool {
	if o == nil || o.IsPremium == nil {
		var ret bool
		return ret
	}
	return *o.IsPremium
}

// GetIsPremiumOk returns a tuple with the IsPremium field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetIsPremiumOk() (*bool, bool) {
	if o == nil || o.IsPremium == nil {
		return nil, false
	}
	return o.IsPremium, true
}

// HasIsPremium returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasIsPremium() bool {
	if o != nil && o.IsPremium != nil {
		return true
	}

	return false
}

// SetIsPremium gets a reference to the given bool and assigns it to the IsPremium field.
func (o *InlineResponse2003DataUser) SetIsPremium(v bool) {
	o.IsPremium = &v
}

// GetIsSubscribed returns the IsSubscribed field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetIsSubscribed() bool {
	if o == nil || o.IsSubscribed == nil {
		var ret bool
		return ret
	}
	return *o.IsSubscribed
}

// GetIsSubscribedOk returns a tuple with the IsSubscribed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetIsSubscribedOk() (*bool, bool) {
	if o == nil || o.IsSubscribed == nil {
		return nil, false
	}
	return o.IsSubscribed, true
}

// HasIsSubscribed returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasIsSubscribed() bool {
	if o != nil && o.IsSubscribed != nil {
		return true
	}

	return false
}

// SetIsSubscribed gets a reference to the given bool and assigns it to the IsSubscribed field.
func (o *InlineResponse2003DataUser) SetIsSubscribed(v bool) {
	o.IsSubscribed = &v
}

// GetIsTrial returns the IsTrial field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetIsTrial() bool {
	if o == nil || o.IsTrial == nil {
		var ret bool
		return ret
	}
	return *o.IsTrial
}

// GetIsTrialOk returns a tuple with the IsTrial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetIsTrialOk() (*bool, bool) {
	if o == nil || o.IsTrial == nil {
		return nil, false
	}
	return o.IsTrial, true
}

// HasIsTrial returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasIsTrial() bool {
	if o != nil && o.IsTrial != nil {
		return true
	}

	return false
}

// SetIsTrial gets a reference to the given bool and assigns it to the IsTrial field.
func (o *InlineResponse2003DataUser) SetIsTrial(v bool) {
	o.IsTrial = &v
}

// GetPremiumUntil returns the PremiumUntil field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetPremiumUntil() int64 {
	if o == nil || o.PremiumUntil == nil {
		var ret int64
		return ret
	}
	return *o.PremiumUntil
}

// GetPremiumUntilOk returns a tuple with the PremiumUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetPremiumUntilOk() (*int64, bool) {
	if o == nil || o.PremiumUntil == nil {
		return nil, false
	}
	return o.PremiumUntil, true
}

// HasPremiumUntil returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasPremiumUntil() bool {
	if o != nil && o.PremiumUntil != nil {
		return true
	}

	return false
}

// SetPremiumUntil gets a reference to the given int64 and assigns it to the PremiumUntil field.
func (o *InlineResponse2003DataUser) SetPremiumUntil(v int64) {
	o.PremiumUntil = &v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetLang() string {
	if o == nil || o.Lang == nil {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetLangOk() (*string, bool) {
	if o == nil || o.Lang == nil {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasLang() bool {
	if o != nil && o.Lang != nil {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *InlineResponse2003DataUser) SetLang(v string) {
	o.Lang = &v
}

// GetPreferedDomain returns the PreferedDomain field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetPreferedDomain() string {
	if o == nil || o.PreferedDomain == nil {
		var ret string
		return ret
	}
	return *o.PreferedDomain
}

// GetPreferedDomainOk returns a tuple with the PreferedDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetPreferedDomainOk() (*string, bool) {
	if o == nil || o.PreferedDomain == nil {
		return nil, false
	}
	return o.PreferedDomain, true
}

// HasPreferedDomain returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasPreferedDomain() bool {
	if o != nil && o.PreferedDomain != nil {
		return true
	}

	return false
}

// SetPreferedDomain gets a reference to the given string and assigns it to the PreferedDomain field.
func (o *InlineResponse2003DataUser) SetPreferedDomain(v string) {
	o.PreferedDomain = &v
}

// GetFidelityPoints returns the FidelityPoints field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetFidelityPoints() int64 {
	if o == nil || o.FidelityPoints == nil {
		var ret int64
		return ret
	}
	return *o.FidelityPoints
}

// GetFidelityPointsOk returns a tuple with the FidelityPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetFidelityPointsOk() (*int64, bool) {
	if o == nil || o.FidelityPoints == nil {
		return nil, false
	}
	return o.FidelityPoints, true
}

// HasFidelityPoints returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasFidelityPoints() bool {
	if o != nil && o.FidelityPoints != nil {
		return true
	}

	return false
}

// SetFidelityPoints gets a reference to the given int64 and assigns it to the FidelityPoints field.
func (o *InlineResponse2003DataUser) SetFidelityPoints(v int64) {
	o.FidelityPoints = &v
}

// GetLimitedHostersQuotas returns the LimitedHostersQuotas field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetLimitedHostersQuotas() map[string]int64 {
	if o == nil || o.LimitedHostersQuotas == nil {
		var ret map[string]int64
		return ret
	}
	return *o.LimitedHostersQuotas
}

// GetLimitedHostersQuotasOk returns a tuple with the LimitedHostersQuotas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetLimitedHostersQuotasOk() (*map[string]int64, bool) {
	if o == nil || o.LimitedHostersQuotas == nil {
		return nil, false
	}
	return o.LimitedHostersQuotas, true
}

// HasLimitedHostersQuotas returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasLimitedHostersQuotas() bool {
	if o != nil && o.LimitedHostersQuotas != nil {
		return true
	}

	return false
}

// SetLimitedHostersQuotas gets a reference to the given map[string]int64 and assigns it to the LimitedHostersQuotas field.
func (o *InlineResponse2003DataUser) SetLimitedHostersQuotas(v map[string]int64) {
	o.LimitedHostersQuotas = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *InlineResponse2003DataUser) GetNotifications() []string {
	if o == nil || o.Notifications == nil {
		var ret []string
		return ret
	}
	return *o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003DataUser) GetNotificationsOk() (*[]string, bool) {
	if o == nil || o.Notifications == nil {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *InlineResponse2003DataUser) HasNotifications() bool {
	if o != nil && o.Notifications != nil {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given []string and assigns it to the Notifications field.
func (o *InlineResponse2003DataUser) SetNotifications(v []string) {
	o.Notifications = &v
}

func (o InlineResponse2003DataUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.IsPremium != nil {
		toSerialize["isPremium"] = o.IsPremium
	}
	if o.IsSubscribed != nil {
		toSerialize["isSubscribed"] = o.IsSubscribed
	}
	if o.IsTrial != nil {
		toSerialize["isTrial"] = o.IsTrial
	}
	if o.PremiumUntil != nil {
		toSerialize["premiumUntil"] = o.PremiumUntil
	}
	if o.Lang != nil {
		toSerialize["lang"] = o.Lang
	}
	if o.PreferedDomain != nil {
		toSerialize["preferedDomain"] = o.PreferedDomain
	}
	if o.FidelityPoints != nil {
		toSerialize["fidelityPoints"] = o.FidelityPoints
	}
	if o.LimitedHostersQuotas != nil {
		toSerialize["limitedHostersQuotas"] = o.LimitedHostersQuotas
	}
	if o.Notifications != nil {
		toSerialize["notifications"] = o.Notifications
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2003DataUser struct {
	value *InlineResponse2003DataUser
	isSet bool
}

func (v NullableInlineResponse2003DataUser) Get() *InlineResponse2003DataUser {
	return v.value
}

func (v *NullableInlineResponse2003DataUser) Set(val *InlineResponse2003DataUser) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2003DataUser) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2003DataUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2003DataUser(val *InlineResponse2003DataUser) *NullableInlineResponse2003DataUser {
	return &NullableInlineResponse2003DataUser{value: val, isSet: true}
}

func (v NullableInlineResponse2003DataUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2003DataUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


