/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20019Data struct for InlineResponse20019Data
type InlineResponse20019Data struct {
	Message *string `json:"message,omitempty"`
}

// NewInlineResponse20019Data instantiates a new InlineResponse20019Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20019Data() *InlineResponse20019Data {
	this := InlineResponse20019Data{}
	return &this
}

// NewInlineResponse20019DataWithDefaults instantiates a new InlineResponse20019Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20019DataWithDefaults() *InlineResponse20019Data {
	this := InlineResponse20019Data{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InlineResponse20019Data) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20019Data) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InlineResponse20019Data) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InlineResponse20019Data) SetMessage(v string) {
	o.Message = &v
}

func (o InlineResponse20019Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20019Data struct {
	value *InlineResponse20019Data
	isSet bool
}

func (v NullableInlineResponse20019Data) Get() *InlineResponse20019Data {
	return v.value
}

func (v *NullableInlineResponse20019Data) Set(val *InlineResponse20019Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20019Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20019Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20019Data(val *InlineResponse20019Data) *NullableInlineResponse20019Data {
	return &NullableInlineResponse20019Data{value: val, isSet: true}
}

func (v NullableInlineResponse20019Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20019Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


