/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2003Data struct for InlineResponse2003Data
type InlineResponse2003Data struct {
	User *InlineResponse2003DataUser `json:"user,omitempty"`
}

// NewInlineResponse2003Data instantiates a new InlineResponse2003Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2003Data() *InlineResponse2003Data {
	this := InlineResponse2003Data{}
	return &this
}

// NewInlineResponse2003DataWithDefaults instantiates a new InlineResponse2003Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2003DataWithDefaults() *InlineResponse2003Data {
	this := InlineResponse2003Data{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *InlineResponse2003Data) GetUser() InlineResponse2003DataUser {
	if o == nil || o.User == nil {
		var ret InlineResponse2003DataUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Data) GetUserOk() (*InlineResponse2003DataUser, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *InlineResponse2003Data) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given InlineResponse2003DataUser and assigns it to the User field.
func (o *InlineResponse2003Data) SetUser(v InlineResponse2003DataUser) {
	o.User = &v
}

func (o InlineResponse2003Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2003Data struct {
	value *InlineResponse2003Data
	isSet bool
}

func (v NullableInlineResponse2003Data) Get() *InlineResponse2003Data {
	return v.value
}

func (v *NullableInlineResponse2003Data) Set(val *InlineResponse2003Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2003Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2003Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2003Data(val *InlineResponse2003Data) *NullableInlineResponse2003Data {
	return &NullableInlineResponse2003Data{value: val, isSet: true}
}

func (v NullableInlineResponse2003Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2003Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


