/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse20016Data struct for InlineResponse20016Data
type InlineResponse20016Data struct {
	Links *[]InlineResponse20016DataLinks `json:"links,omitempty"`
}

// NewInlineResponse20016Data instantiates a new InlineResponse20016Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20016Data() *InlineResponse20016Data {
	this := InlineResponse20016Data{}
	return &this
}

// NewInlineResponse20016DataWithDefaults instantiates a new InlineResponse20016Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20016DataWithDefaults() *InlineResponse20016Data {
	this := InlineResponse20016Data{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *InlineResponse20016Data) GetLinks() []InlineResponse20016DataLinks {
	if o == nil || o.Links == nil {
		var ret []InlineResponse20016DataLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20016Data) GetLinksOk() (*[]InlineResponse20016DataLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *InlineResponse20016Data) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []InlineResponse20016DataLinks and assigns it to the Links field.
func (o *InlineResponse20016Data) SetLinks(v []InlineResponse20016DataLinks) {
	o.Links = &v
}

func (o InlineResponse20016Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20016Data struct {
	value *InlineResponse20016Data
	isSet bool
}

func (v NullableInlineResponse20016Data) Get() *InlineResponse20016Data {
	return v.value
}

func (v *NullableInlineResponse20016Data) Set(val *InlineResponse20016Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20016Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20016Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20016Data(val *InlineResponse20016Data) *NullableInlineResponse20016Data {
	return &NullableInlineResponse20016Data{value: val, isSet: true}
}

func (v NullableInlineResponse20016Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20016Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


