/*
Alldebrid API

Welcome to the OpenAPI Alldebrid API v4 !<br /> You can use this API to access various Alldebrid services from custom applications or scripts.<br /> <br /> API is organized around REST,<br /> returns JSON-encoded responses and use standard HTTP response codes.<br /> <br /> All calls are to be made on the HTTPS endpoints.<br /> Some are public, others require to be authentificated with an apikey (see Authentication).<br /> <br /> You must also identify your apps or script with a meaningfull agent parameter.<br /> <br /> This API version is namespaced as v4, as such all endpoint start with /v4/,<br /> such like http://api.alldebrid.com/v4/ping?agent=apiShowcase.<br /> <br /> This API v4 should be the final version regarding general response format and errors (hopefully).<br />

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineResponse2004Data struct for InlineResponse2004Data
type InlineResponse2004Data struct {
	Message *string `json:"message,omitempty"`
}

// NewInlineResponse2004Data instantiates a new InlineResponse2004Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2004Data() *InlineResponse2004Data {
	this := InlineResponse2004Data{}
	return &this
}

// NewInlineResponse2004DataWithDefaults instantiates a new InlineResponse2004Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2004DataWithDefaults() *InlineResponse2004Data {
	this := InlineResponse2004Data{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *InlineResponse2004Data) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2004Data) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *InlineResponse2004Data) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *InlineResponse2004Data) SetMessage(v string) {
	o.Message = &v
}

func (o InlineResponse2004Data) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2004Data struct {
	value *InlineResponse2004Data
	isSet bool
}

func (v NullableInlineResponse2004Data) Get() *InlineResponse2004Data {
	return v.value
}

func (v *NullableInlineResponse2004Data) Set(val *InlineResponse2004Data) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2004Data) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2004Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2004Data(val *InlineResponse2004Data) *NullableInlineResponse2004Data {
	return &NullableInlineResponse2004Data{value: val, isSet: true}
}

func (v NullableInlineResponse2004Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2004Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


