/*
 * Alldebrid API
 *
 * Welcome to the Alldebrid API v4 ! You can use this API to access various Alldebrid services from custom applications or scripts.
 *
 * API version: 4.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Status string `json:"status,omitempty"`
	Data *interface{} `json:"data,omitempty"`
}
